---
- name: golang download
  shell: |
    curl -fsSL https://golang.org/dl/go{{ golang_version }}.linux-amd64.tar.gz -O

- name: golang install
  shell: |
    tar -C /usr/local -xzf go{{ golang_version }}.linux-amd64.tar.gz