---
- name: golang download
  ansible.builtin.shell: |
    curl -fsSL https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz -O

- name: golang install
  ansible.builtin.shell: |
    tar -C /usr/local -xzf go{{ golang_version }}.linux-amd64.tar.gz