---
- name: install version terraform bin
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ hashicorp_terraform_version }}/terraform_{{ hashicorp_terraform_version }}_{{ hashicorp_terraform_os }}_amd64.zip
    dest: /usr/local/bin
    remote_src: yes