---
- name: installing vs code ide
  block:
  - name: add signing key without apt-key
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /etc/apt/trusted.gpg.d/microsoft.asc
  - name: add vs code repo
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
      filename: vscode
      state: present
  - ansible.builtin.apt:
      name: code
      state: present
      update_cache: yes
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo
  become_user: root
  tags:
    - ide-vscode
