---
- name: installing kvm
  block:
  - name: installing deps and tools
    ansible.builtin.apt:
      name:    
      - virt-manager
      - qemu-kvm 
      - libvirt-clients 
      - libvirt-daemon-system 
      - bridge-utils 
      - libguestfs-tools 
      - genisoimage 
      - virtinst 
      - libosinfo-bin
      update_cache: yes
    register: _setup_kvm
    when: 
      - ansible_facts['os_family'] == "Debian"

  - name: adding user profile to libvirt group
    ansible.builtin.user:
      name: "{{ profile_user }}"
      groups: libvirt,libvirt-qemu
      append: yes
    when: _setup_kvm is succeeded
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo
  become_user: root
  tags:
    - kvm