---
- name: Add variables OS specific
  include_vars: "{{ ansible_os_family }}.yml"

- name: Configure timezone
  include: timezone.yml

- name: Set profile user sudoers
  include: sudoers.yml

- name: Apply if FamilyOS is Debian
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Apply if Centos
  include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Configure terminator
  include: terminator.yml

- name: Configure shell
  include: shell.yml
