---
- name: add variables OS specific
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure timezone
  include_tasks: timezone.yml

- name: set profile user sudoers
  include_tasks: sudoers.yml

- name: apply if family os is Debian
  block:
    - include_tasks: apt_packages.yml
      tags: install-apt-pkg
    - include_tasks: chrome.yml
      tags: install-chrome
    - include_tasks: pip_packages.yml
      tags: install-pip-pkg
    - name: setup kvm
      include_tasks: kvm.yml
      when: setup_kvm == true
      tags: kvm
    - include_tasks: ide_vscode.yml
      tags: ide-vscode
    - include_tasks: nodejs.yml
      when: setup_nodejs == true
      tags: nodejs
  when: ansible_os_family == 'Debian'

- name: apply if Centos
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: configure kitty
  include_tasks: kitty.yml
  when: setup_kitty == true
  tags: kitty

- name: configure terminator
  include_tasks: terminator.yml
  when: setup_terminator == true
  tags: terminator

- name: configure shell
  include_tasks: shell.yml
  tags:
    - powerline-shell

- name: setup docker and docker compose
  include_tasks: docker.yml
  tags:
    - docker
    - docker-compose

- name: setup golang
  include_tasks: golang.yml
  when: setup_golang == true
  ignore_errors: true
  tags: golang

- name: setup hashicorp bin
  include_tasks: hashicorp.yml
  when: setup_hashicorp == true
  tags: hashicorp

- name: setup desktop install-desktop-gui
  include_tasks: desktop_gui.yml
  when: setup_desktop_gui == true
  tags: 
   - install-desktop-gui
   - update-desktop-gui-i3-config

- name: setup kubernetes tools
  block:
    - ansible.builtin.include_tasks:
        file: jsonnet.yml
    - ansible.builtin.include_tasks:
        file: tanka.yml
    - ansible.builtin.include_tasks:
        file: helm.yml
  when: setup_kubernetes_tools == true
  tags: 
    - helm
    - jsonnet
    - tanka

- debug:
    msg:
    - "There are no errors? Restart your pc to effect user changes."
