---
- name: add variables OS specific
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure timezone
  include: timezone.yml

- name: set profile user sudoers
  include: sudoers.yml

- name: apply if FamilyOS is Debian
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: apply if Centos
  include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: configure terminator
  include: terminator.yml

- name: configure shell
  include: shell.yml

- name: setup docker and docker compose
  include: docker.yml

- name: setup kvm
  include: kvm.yml
  when: setup_kvm == true

- name: setup IDE VS code
  include: ide_code.yml
  when: ansible_os_family == 'Debian'

- name: setup nodejs
  include: nodejs.yml
  when: ansible_os_family == 'Debian' and setup_nodejs == true

- name: setup hashicorp bin
  include: hashicorp.yml
  when: setup_hashicorp == true

- debug:
    msg:
    - "There are no errors? Restart your pc to effect user changes."
