---
# Variables
- name: Add variables OS specific
  include_vars: "{{ ansible_os_family }}.yml"

# Provision configuration
- name: Apply if FamilyOS is Debian
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Apply if Centos
  include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
