---
- name: add nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: add nodesource repositories for node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: install nodejs
  apt:
    name:
      - "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
    update_cache: yes
    state: present
  register: install_nodejs

- name: install npm expo-cli 
  npm:
    name: expo-cli
    version: "{{ npm_version_expo_cli }}"
    global: yes
  when: install_nodejs is succeeded and setup_expo_cli == true 