---
- name: add nodesource apt key.
  block:
    - ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        state: present
        keyring: /etc/apt/keyrings/nodesource.gpg
    - name: add nodesource repositories for node.js.
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    - name: install nodejs
      ansible.builtin.apt:
        name:
          - "nodejs={{ nodejs_version|regex_replace('x', '') }}*"
        update_cache: yes
        state: present
      register: install_nodejs
    - name: install npm expo-cli 
      npm:
        name: expo-cli
        version: "{{ npm_version_expo_cli }}"
        global: yes
      when: install_nodejs is succeeded and setup_expo_cli == true 
  tags:
    - nodejs