---
- name: install pip packages
  block:
    - name: install pipx
      ansible.builtin.apt:
        name: pipx
        state: present
    - name: install require pip packages
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      loop: "{{ requirements_install_pip_packages }}"
    - name: pip custom packages
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      loop: "{{ install_pip_packages }}"
      when: install_pip_packages != []
  become: true
  become_method: sudo
  become_user: root
  tags:
    - install-pip-pkg