---
- name: install requires apt  
  apt:
    name:
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
    update_cache: yes

- name: Google Chrome apt-key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Google Chrome repository
  lineinfile:
    dest: /etc/apt/sources.list.d/google.list
    line: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    create: yes

- name: Install requirements packages
  apt:
    name: "{{ requirements_install_packages }}"
    update_cache: yes
    state: latest

- name: Install pip requirements packages
  pip:
    name: "{{ requirements_install_pip_packages }}"
    state: latest
    executable: pip3

- name: Install custom pip packages
  pip:
    name: "{{ install_pip_packages }}"
    state: latest
    executable: pip3
  ignore_errors: yes
  when: install_pip_packages != ""

- name: Install apt custom packages
  apt:
    name: "{{ install_packages }}"
    update_cache: yes
    autoremove: yes
    autoclean: yes
  ignore_errors: yes
