---
- name: setup powerline-shell
  ansible.builtin.blockinfile:
    dest: /etc/bash.bashrc
    insertafter: EOF
    content: |
      function _update_ps1() {
        PS1=$(powerline-shell $?)
      }
      if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
         PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi